### PR TITLE
Fix removeRetiredJob action import for JobMonitor

### LINKED ISSUE #254: removeRetiredJob action import (for type) interfering with props function
Looks like since the flow typing of actions, `removeRetiredJob` in the JobMonitor has been negatively impacted due to import/props ambiguity in this commit: https://github.com/catalogueglobal/datatools-ui/commit/0c2c4631ddee5d21791b0d7c15af71a79d9a3686#diff-8d290610f45faf4873f9b194defa375eR151

Since `removeRetiredJob` is being imported for type definition, it probably appeared that the function had been destructured from the props, but it is no longer working properly.

I worry that importing the actions in this way sets us up for similar problems. Maybe we can alter the syntax for action imports in components from:
```
import {
  fetchAppInfo,
  removeRetiredJob,
  startJobMonitor,
  setJobMonitorVisible
} from '../../manager/actions/status'
```

to 

```
import * as statusActions from '../../manager/actions/status'

type {
  removeRetiredJob: statusActions.removeRetiredJob
}
```

### PR DESCRIPTION
**Pull request by landonreed**
fixes #254

### CODE REVIEW

File: lib/common/components/Sidebar.js [hunk 1]
```diff
@@ -36,16 +31,16 @@ type Props = {
   appInfo: AppInfo,
   children: Node,
   expanded: boolean,
-  fetchAppInfo: typeof fetchAppInfo,
+  fetchAppInfo: typeof statusActions.fetchAppInfo,
```
Comment (evansiroky) [inline lib/common/components/Sidebar.js:34]: Much better way to import these actions than before.  👍

**Review by evansiroky — APPROVED** [review]
Approved assuming merge conflicts resolved.
